version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always
    networks:
      - secilstore-network

  # Redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - secilstore-network

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always
    networks:
      - secilstore-network

  configwebui:
    build:
      context: .
      dockerfile: SecilStore_ConfigWebUI/Dockerfile
    container_name: configwebui
    ports:
      - "8090:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDB__ConnectionString=mongodb://mongodb:27017
      - MongoDB__DatabaseName=ConfigurationDb
      - MongoDB__CollectionName=Configurations
      - RabbitMQ__ConnectionString=amqp://guest:guest@rabbitmq:5672
      - RabbitMQ__UseRabbitMQ=true
    depends_on:
      - mongodb
      - redis
      - rabbitmq
    restart: always
    networks:
      - secilstore-network

networks:
  secilstore-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
  rabbitmq_data: 
